---
title: "Marleigh's work"
author: "Marleigh Jenkins-Morse"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(lubridate)
library(ggmap)
library(babynames)
library(plotly)
library(gganimate) 
library(gifski) 
```

```{r}
library("httr")
library("readxl")
GET("https://query.data.world/s/6fdq5xwdl4pmw5iq7pgoemzofzvqkp", write_disk(tf <- tempfile(fileext = ".xlsx")))
NBA_Annual_Attendance <- read_excel(tf)
```

```{r}
NBA_Annual_Attendance %>% 
  group_by(`Starting Year`) %>% 
  ggplot(aes(y= `Home: Avg Attendance`, x= `Starting Year`, color= Team))+
  geom_line()
```
```{r}
NBA_Annual_Attendance %>% 
  filter(`Starting Year` == 2000) %>% 
  ggplot(aes(y= `Home: Total Attendance`, x= `Starting Year`, fill= Team))+
  geom_col()
```

```{r}
NBA_Annual_Attendance %>% 
  filter(`Starting Year` == 2014) %>% 
  ggplot(aes(y= `Home: Total Attendance`, x= `Starting Year`, fill= Team))+
  geom_col()
```

```{r}
NBA_Annual_Attendance %>% 
  filter(Team == 'Bulls') %>% 
  ggplot(aes(y= `Home: Avg Attendance`, x= `Starting Year`, fill= Team))+
  geom_line()

```

```{r}
international_players<-zcm7h7bwdig7dcrxe5cc7g7d5cctu2
player_salary <- X7krc2hcuja6c3fw5m6po2m53qo6smi
```

```{r}
new <- international_players %>% 
  left_join(all_seasons, by= "draft_year")
  
new
```

```{r}
salary_new <-new %>% 
  full_join(player_salary, by=c("_id"="player_id"))

salary_new
```




