---
title: "NBA Stats Dataset"
author: "Michael Lockhart"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(readr)
library(tidyverse)
library(readxl)
library(maps)
library(ggthemes)
library(ggmap)
library(plotly)
library(ggplot2)
```

```{r, message=FALSE}
all_seasons <- read_csv("all_seasons.csv")
```

```{r, message=FALSE}
nbaStats <- read_csv("nbaStats.csv")
```

```{r, message=FALSE}
NBA_Players_by_State <- read_excel("NBA Players by State.xlsx")
```

# NBA_Players_by_State Variable Key

```{r, message=FALSE}
Player_Stats_1996_2016 <- read_csv("all_seasons.csv")
```

```{r}
NBA_Players_birthplace <- NBA_Players_by_State %>% 
  select(Player, Date, City, State)
```


```{r}
nbaNew <- nbaStats %>% 
  select(Player, Status, Pos, labels, g, mp, FG, FGA, `3P`, 
         `3PA`, FTA, `FT%`, TRB, AST, STL, TOV, PTS) %>% 
  left_join(NBA_Players_birthplace, by = "Player") %>% 
  filter(!is.na(Date)) %>% 
  filter(!is.na(City)) %>% 
  mutate(state_new= tolower(ifelse(State=="DC", "district of columbia", State))) 
```

```{r}
games_per_state <- nbaNew %>% 
  group_by(state_new) %>% 
  filter(Status == "Active") %>% 
  summarise(games = sum(g)) %>% 
  arrange(desc(games))
```


```{r fig.width=10}
states_map <- map_data("state")

  games_map <- ggplot(games_per_state, aes(fill = games)) +
  geom_map(aes(map_id = state_new), map = states_map) +
  expand_limits(x = states_map$long, y = states_map$lat) + 
  theme_map()+
  scale_fill_distiller(palette = "Spectral")+
  labs(title = "Games Played per State by Active Players as of 2017")

ggplotly(games_map)

```

```{r}
PTS_per_State <- nbaNew %>% 
  group_by(state_new) %>% 
  filter(Status == "Active") %>% 
  summarise(pts_avg = mean(PTS)) %>% 
  arrange(desc(pts_avg))
```


```{r fig.width=10}
states_map <- map_data("state")

PTS_per_State %>% 
  ggplot(aes(fill = pts_avg)) +
  geom_map(aes(map_id = state_new), map = states_map) +
  expand_limits(x = states_map$long, y = states_map$lat) + 
  theme_map()+
  scale_fill_distiller(palette = "Spectral") +
  labs(title = "Points Scored per State by Active Players as of 2017")

```







```{r}
dist_countries <- all_seasons %>% 
  group_by(season) %>% 
  distinct(country) %>% 
  count(country) %>% 
  summarise(total_countries = sum(n)) 
```

```{r}
  total_countries <- ggplot(dist_countries, aes(x = season, y = total_countries))+
  geom_col()+
  coord_flip()+
  labs(title = "Number of Countries Represented in the NBA per Season", x = "Total Number of Countries", y = "NBA Season") 
  
ggplotly(total_countries)
```


Next Visualization: 
  Draft position of players from Foreign countries. Summarise the foreign countries  Don't want duplicates so groupby player so you can filter out the duplicates. group by country and summarise the mean of draft_number 

```{r}
dist_players <- all_seasons %>% 
distinct(player_name,.keep_all = TRUE) %>% 
  select(player_name, country, draft_number)
```

#draft number by country
```{r}
dist_players%>% 
  #filter(country != "USA") %>% 
  filter(draft_number != "undrafted") %>% 
  filter(draft_number != "Undrafted") %>% 
  mutate(draft_pos = as.numeric(draft_number)) %>% 
  group_by(country) %>%  
  summarize(mean = mean(draft_pos)) %>%
  arrange(desc(mean)) %>% 
  ggplot(aes(x=fct_inorder(country), y=mean)) +
 geom_bar(stat = "identity")+
  coord_flip()
```

  



